@urlPrefix = https://green-voice-3640.us-east1.kalix.app
@generatorId = "generator-6"
@position = { "lat": 40.7128, "lng": -74.0060 }
@radiusKm = 500
@deviceCountLimit = 500
@ratePerSecond = 50

###

POST {{urlPrefix}}/generator/{{generatorId}}/create
Content-Type: application/json

{
  "generatorId":{{generatorId}},
  "position":{{position}},
  "radiusKm":{{radiusKm}},
  "deviceCountLimit":{{deviceCountLimit}},
  "ratePerSecond":{{ratePerSecond}}
}

###

GET {{urlPrefix}}/generator/{{generatorId}}

###

PUT {{urlPrefix}}/generator/{{generatorId}}/generate
Content-Type: application/json

{
  "generatorId":{{generatorId}}
}
