@urlPrefix = https://green-voice-3640.us-east1.kalix.app
@generatorId = generator-1
@position = { "lat": 20.0, "lng": 10.0 }
@radiusKm = 10
@deviceCountLimit = 100
@ratePerSecond = 10
# @topLeftLat = 11.0
# @topLeftLng = 10.0
# @botRightLat = 9.0
# @botRightLng = 11.0
@topLeftLat = 90.0
@topLeftLng = 0.0
@botRightLat = -90.0
@botRightLng = 180.0

###

POST {{urlPrefix}}/generator/{{generatorId}}/create
Content-Type: application/json

{
  "generatorId":"{{generatorId}}",
  "position":{{position}},
  "radiusKm":{{radiusKm}},
  "deviceCountLimit":{{deviceCountLimit}},
  "ratePerSecond":{{ratePerSecond}}
}

###

PUT {{urlPrefix}}/generator/{{generatorId}}/generate
Content-Type: application/json

{
  "generatorId":"{{generatorId}}"
}

###

GET {{urlPrefix}}/generator/{{generatorId}}

###

GET {{urlPrefix}}/generators/by-location/{{topLeftLat}}/{{topLeftLng}}/{{botRightLat}}/{{botRightLng}}
