@urlPrefix = https://green-voice-3640.us-east1.kalix.app

# Covers the whole world
@zoom = 1
@topLeftLat = 90.0
@topLeftLng = 0.0
@botRightLat = -90.0
@botRightLng = 180.0

# @zoom = 17
# @topLeftLat = 20.01
# @topLeftLng = 9.99
# @botRightLat = 19.99
# @botRightLng = 10.01

###

GET {{urlPrefix}}/regions/by-location/{{zoom}}/{{topLeftLat}}/{{topLeftLng}}/{{botRightLat}}/{{botRightLng}}
